# controllers:
#     resource: ../src/Controller/
#     type: annotation

# kernel:
#     resource: ../src/Kernel.php
#     type: annotation

# product_view:
#     path: /product/{id}
#     controller: App/Controller/ProductController::getProduct
#     methods: GET